name: Bank
main: Minuha\Bank
version: "1.0"
api: [3.0.0-ALPHA9]
author: Kkora
description: Bank plugin - Vietnamese
website: https://github.com/Kkora2k3

commands:
 nganhang:
  permission: nganhang.cmd
  description: Ngân Hàng
  usage: /nganhang <amount>

permissions:
 nganhang.cmd:
  default: true
  description: Bank command.
